### ISSUE TITLE
Is there a way to create mounts based on the names instead of GUIDs ?

### ISSUE THREAD

**Issue by alwaysastudent** [hashicorp/cf-vault-service-broker#8]
Hi, Currently the namespaces created dynamically for secret mounts looks very random and tightly coupled to the GUIDs generated on a CF/PCF ecosystem. Can this be made a bit name based instead of GUID for ease of management ?
```
 "VCAP_SERVICES": {
  "hashicorp-vault": [
   {
    "credentials": {
     "address": "https://blah.amazonaws.com:8200/",
     "auth": {
      "accessor": "25afc1eb-5ef7-1cbf-2aca-62468ac913af",
      "token": "d3a9123e-5c19-7562-432e-ebb763bae079"
     },
     "backends": {
      "generic": "cf/7abe1cfa-4a17-407a-8bf9-09f1544951c7/secret",
      "transit": "cf/7abe1cfa-4a17-407a-8bf9-09f1544951c7/transit"
     },
     "backends_shared": {
      "organization": "cf/9a9fb216-42ae-4bfb-865e-69b44e256a98/secret",
      "space": "cf/d0cae1cd-e4e2-44f4-9718-a1f6d54d605b/secret"
     }
    },
    "label": "hashicorp-vault",
    "name": "aws-vault",
    "plan": "shared",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     ""
    ],
    "volume_mounts": []
   }
```

```
 cf org my-org --guid
9a9fb216-42ae-4bfb-865e-69b44e256a98
```
```
cf space my-space --guid
d0cae1cd-e4e2-44f4-9718-a1f6d54d605b
```

It looks pretty weird since it is very random

Ideally speaking these would have been better placed if it were mounted based on names.

cf/my-org/secret
cf/my-space/secret
cf/my-app/secret (instead of the instance id)

**Comment by sethvargo** [comment]
Hi @alwaysastudent 

Thank you for opening an issue. This is, unfortunately, not possible because GF allows you to mount the same application multiple times. Internally, the UUIDs of the org, space, and service are the only thing that's guaranteed to be unique. 

However, when you bind the service, the `VCAP_SERVICES` envvar will be populated with the above JSON. That JSON includes all the path and URL information for the query, so you can easily build it up. You don't need to "guess" the org/space ides because they come back under the respective paths in the JSON payload.

Please let me know if you have any additional questions.

**Comment by alwaysastudent** [comment]
The issue with the guids is they are generated after the fact that the app has been pushed and bound to the service. So an admin would not be having these mounts on the vault server beforehand for him to pre configure the secrets.  Or at least it is not straightforward. I guess he can go do the cf commands and find the guids for org and space. But it still sounds clunky.

**Comment by alwaysastudent** [comment]
@sethvargo kindly consider this opinion

**Comment by sethvargo** [comment]
Hi @alwaysastudent 

We are not going to do this. It is against what the CF team has recommended.
